[package]
name = "chinamaxxbom-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chinamaxxbom-core = { path = "../chinamaxxbom-core" }
anyhow.workspace = true
serde_json.workspace = true
pico-args = "0.5"


[[bin]]
name = "chinamaxxbom"
path = "src/main.rs"

[dev-dependencies]
tempfile.workspace = true
